# ==============================================================
# Configuration globale de l'application
# ==============================================================
spring.application.name=AniSdoufBack

# ==============================================================
# Configuration de la Base de données
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/anisdouf_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# ==============================================================
# Configuration JPA / HIBERNATE
# ==============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# Configuration de la Sécurité (JWT / CORS)
# ==============================================================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
app.cors.frontend-url=http://localhost:4200
