# Configuration globale de l'application
spring.application.name=AniSdoufBack

# Configuration de la Base de donnees
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=postgres.gvwohsprxgniqgpgmway
spring.datasource.password=${DB_PASSWORD}

# Configuration JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configuration de la Securite (JWT / CORS)
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
app.cors.frontend-url=http://localhost:4200
